server:
  port: 8080

camel:
  servlet:
    mapping:
      context-path: /api/*
  springboot:
    name: base-price-retrieval
    main-run-controller: true

app:
  baseprice:
    base-url: "http://localhost:8080/api"
  fakestore:
    base-url: "https://fakestoreapi.com"
  exchangerate:
    base-url: "https://api.exchangerate-api.com"
  shippo:
    base-url: "https://api.goshippo.com"

# Resilience4j configurations can also be handled within Camel Route directly or application properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      fakestore:
        baseConfig: default
      baseprice:
        baseConfig: default
      exchangerate:
        baseConfig: default
      shippo:
        baseConfig: default
